name: Frontend CI/CD

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      working-directory: client
      run: npm install

    - name: Build frontend
      working-directory: client
      run: npm run build

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@latest
      with:
        app_location: 'client'
        output_location: 'client/build'
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
