name: blog frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflow/frontend-appservice.yml"
  workflow_dispatch:

env: 
  NODE_VERSION: '18.x'

permissions:
  contents: read
  id-token: write # Required for Azure login

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Azure CLI Login
        uses: azure/login@v2
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: blog-app-frontend
          package: ./dist
